// Auto-generated
let project = new Project('Simple Pool');

project.addSources('Sources');
project.addLibrary("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/armory");
project.addLibrary("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/iron");
project.addLibrary("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/lib/haxebullet");
project.addAssets("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('--no-inline');
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('phfa.node.FirstRound');
project.addParameter("--macro keep('phfa.node.FirstRound')");
project.addParameter('phfa.node.Rearm');
project.addParameter("--macro keep('phfa.node.Rearm')");
project.addParameter('phfa.node.PauseMenu');
project.addParameter("--macro keep('phfa.node.PauseMenu')");
project.addParameter('phfa.node.BallUniqueWhite');
project.addParameter("--macro keep('phfa.node.BallUniqueWhite')");
project.addParameter('phfa.node.ShotChecker');
project.addParameter("--macro keep('phfa.node.ShotChecker')");
project.addParameter('phfa.node.GroupBalls');
project.addParameter("--macro keep('phfa.node.GroupBalls')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('phfa.node.MainMenu');
project.addParameter("--macro keep('phfa.node.MainMenu')");
project.addParameter('phfa.node.Shot');
project.addParameter("--macro keep('phfa.node.Shot')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('phfa.node.BallUniqueBlack');
project.addParameter("--macro keep('phfa.node.BallUniqueBlack')");
project.addShaders("build_SimplePool/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_SimplePool/compiled/Assets/**", { notinlist: true });
project.addAssets("build_SimplePool/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("Bundled/BallsDiffuse.jpg", { notinlist: true });
project.addAssets("Bundled/Icon.png", { notinlist: true });
project.addAssets("Bundled/TableDiffuse.jpg", { notinlist: true });
project.addAssets("Bundled/World.hdr", { notinlist: true });
project.addAssets("Bundled/canvas/Intro.files", { notinlist: true });
project.addAssets("Bundled/canvas/Intro.json", { notinlist: true });
project.addAssets("Bundled/canvas/MainMenu.files", { notinlist: true });
project.addAssets("Bundled/canvas/MainMenu.json", { notinlist: true });
project.addAssets("Bundled/canvas/PauseMenu.files", { notinlist: true });
project.addAssets("Bundled/canvas/PauseMenu.json", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addLibrary("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/lib/zui");
project.addAssets("/mnt/5A01071800E170B0/Armory SDK/2020/light-fix/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_background=World');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_ui');


resolve(project);
