package phfa.node;

@:keep class BallUniqueWhite extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		var _Sequence_001 = new armory.logicnode.SequenceNode(this);
		var _OnContact = new armory.logicnode.OnContactNode(this);
		_OnContact.property0 = "Begin";
		var _Self = new armory.logicnode.SelfNode(this);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		_GetProperty.addInput(_Self, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Local"), 0);
		var _GetObject = new armory.logicnode.GetObjectNode(this);
		_GetObject.addInput(_GetProperty, 0);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(_GetObject, 0);
		var _SetLocation = new armory.logicnode.SetLocationNode(this);
		var _Sequence = new armory.logicnode.SequenceNode(this);
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "Undo";
		_OnEvent_001.addOutputs([_Sequence]);
		_Sequence.addInput(_OnEvent_001, 0);
		var _SetProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_002.addInput(_Sequence, 0);
		_SetProperty_002.addInput(_Self, 0);
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_001.addInput(_Self, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "OnPocket"), 0);
		var _Branch = new armory.logicnode.BranchNode(this);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "Validate";
		_OnEvent.addOutputs([_Branch]);
		_Branch.addInput(_OnEvent, 0);
		_Branch.addInput(_GetProperty_001, 0);
		_Branch.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Sequence_002 = new armory.logicnode.SequenceNode(this);
		_Sequence_002.addInput(_Branch, 1);
		var _SetLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_001.addInput(_Sequence_002, 0);
		_SetLocation_001.addInput(_GetObject, 0);
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_001.addInput(_Self, 0);
		var _SetLocation_002 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_002.addInput(_Sequence, 3);
		_SetLocation_002.addInput(new armory.logicnode.ObjectNode(this, "Direction"), 0);
		_SetLocation_002.addInput(_GetLocation_001, 0);
		_SetLocation_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLocation_003 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_003.addInput(_Sequence_002, 1);
		_SetLocation_003.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_SetLocation_003.addInput(_GetLocation_001, 0);
		_SetLocation_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetLocation_001.addOutputs([_SetLocation_001, _SetLocation_002, _SetLocation_003]);
		_SetLocation_001.addInput(_GetLocation_001, 0);
		_SetLocation_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_002.addOutputs([_SetLocation_001]);
		_Sequence_002.addOutputs([_SetLocation_003]);
		_Branch.addOutputs([_Sequence_002]);
		_GetProperty_001.addOutputs([_Branch]);
		var _SetProperty_009 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_SetProperty_009]);
		_SetProperty_009.addInput(_OnInit, 0);
		_SetProperty_009.addInput(_Self, 0);
		_SetProperty_009.addInput(_GetProperty_001, 1);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_001.addOutputs([_SetProperty_002, _SetProperty_009]);
		_SetProperty_009.addInput(_Boolean_001, 0);
		_SetProperty_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_001.addOutputs([_SetProperty_002, _SetProperty_009]);
		_SetProperty_002.addInput(_GetProperty_001, 1);
		_SetProperty_002.addInput(_Boolean_001, 0);
		_SetProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SetProperty_002]);
		_Sequence.addOutputs([_SetLocation]);
		var _SetVisible_001 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_001.addInput(_Sequence, 2);
		_SetVisible_001.addInput(_Self, 0);
		_SetVisible_001.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetVisible_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SetVisible_001]);
		_Sequence.addOutputs([_SetLocation_002]);
		_SetLocation.addInput(_Sequence, 1);
		_SetLocation.addInput(_Self, 0);
		_SetLocation.addInput(_GetLocation, 0);
		_SetLocation.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetLocation.addOutputs([_SetLocation]);
		_GetObject.addOutputs([_GetLocation, _SetLocation_001]);
		_GetProperty.addOutputs([_GetObject]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _SetVisible = new armory.logicnode.SetVisibleNode(this);
		_SetVisible.addInput(_Sequence_001, 1);
		_SetVisible.addInput(_Self, 0);
		_SetVisible.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVelocity_001 = new armory.logicnode.SetVelocityNode(this);
		var _OnEvent_002 = new armory.logicnode.OnEventNode(this);
		_OnEvent_002.property0 = "RemovePhysics";
		_OnEvent_002.addOutputs([_SetVelocity_001]);
		_SetVelocity_001.addInput(_OnEvent_002, 0);
		_SetVelocity_001.addInput(_Self, 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVelocity = new armory.logicnode.SetVelocityNode(this);
		var _OnEvent_003 = new armory.logicnode.OnEventNode(this);
		_OnEvent_003.property0 = "RestorePhysics";
		_OnEvent_003.addOutputs([_SetVelocity]);
		_SetVelocity.addInput(_OnEvent_003, 0);
		_SetVelocity.addInput(_Self, 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addOutputs([new armory.logicnode.NullNode(this)]);
		_Self.addOutputs([_OnContact, _SetProperty, _GetProperty, _GetProperty_001, _SetProperty_002, _SetLocation, _GetLocation_001, _SetVisible, _SetVisible_001, _SetProperty_009, _SetVelocity_001, _SetVelocity]);
		_OnContact.addInput(_Self, 0);
		_OnContact.addInput(new armory.logicnode.ObjectNode(this, "TriggerPocket"), 0);
		_OnContact.addOutputs([_Sequence_001]);
		_Sequence_001.addInput(_OnContact, 0);
		_Sequence_001.addOutputs([_SetProperty]);
		_Sequence_001.addOutputs([_SetVisible]);
		_Sequence_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetProperty.addInput(_Sequence_001, 0);
		_SetProperty.addInput(_Self, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "OnPocket"), 0);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean.addOutputs([_SetProperty]);
		_SetProperty.addInput(_Boolean, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}