package phfa.node;

@:keep class GroupBalls extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		var _Sequence_001 = new armory.logicnode.SequenceNode(this);
		var _OnContact = new armory.logicnode.OnContactNode(this);
		_OnContact.property0 = "Begin";
		var _Self = new armory.logicnode.SelfNode(this);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		_GetProperty.addInput(_Self, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Local"), 0);
		var _GetObject = new armory.logicnode.GetObjectNode(this);
		_GetObject.addInput(_GetProperty, 0);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(_GetObject, 0);
		var _SetLocation = new armory.logicnode.SetLocationNode(this);
		var _Sequence_002 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "Undo";
		_OnEvent_001.addOutputs([_Sequence_002]);
		_Sequence_002.addInput(_OnEvent_001, 0);
		var _Branch_001 = new armory.logicnode.BranchNode(this);
		_Branch_001.addInput(_Sequence_002, 0);
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_001.addInput(_Self, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "OnPocket"), 0);
		var _Branch = new armory.logicnode.BranchNode(this);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "Validate";
		_OnEvent.addOutputs([_Branch]);
		_Branch.addInput(_OnEvent, 0);
		_Branch.addInput(_GetProperty_001, 0);
		var _Sequence_003 = new armory.logicnode.SequenceNode(this);
		_Sequence_003.addInput(_Branch, 0);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		_RemoveObject.addInput(_Sequence_003, 0);
		_RemoveObject.addInput(_Self, 0);
		_RemoveObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_003.addOutputs([_RemoveObject]);
		_Branch.addOutputs([_Sequence_003]);
		var _SetLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_001.addInput(_Branch, 1);
		_SetLocation_001.addInput(_GetObject, 0);
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_001.addInput(_Self, 0);
		_GetLocation_001.addOutputs([_SetLocation_001]);
		_SetLocation_001.addInput(_GetLocation_001, 0);
		_SetLocation_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch.addOutputs([_SetLocation_001]);
		_GetProperty_001.addOutputs([_Branch, _Branch_001]);
		var _SetProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_002.addInput(_Sequence_002, 1);
		_SetProperty_002.addInput(_Self, 0);
		_SetProperty_002.addInput(_GetProperty_001, 1);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _SetProperty_008 = new armory.logicnode.SetPropertyNode(this);
		var _Branch_005 = new armory.logicnode.BranchNode(this);
		var _OnVolumeTrigger = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger.property0 = "Leave";
		_OnVolumeTrigger.addInput(_Self, 0);
		_OnVolumeTrigger.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_OnVolumeTrigger.addOutputs([_Branch_005]);
		_Branch_005.addInput(_OnVolumeTrigger, 0);
		var _GetProperty_006 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_006.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_GetProperty_006.addInput(new armory.logicnode.StringNode(this, "TriggeringBall"), 0);
		var _Branch_003 = new armory.logicnode.BranchNode(this);
		var _OnVolumeTrigger_001 = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger_001.property0 = "Overlap";
		_OnVolumeTrigger_001.addInput(_Self, 0);
		_OnVolumeTrigger_001.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_OnVolumeTrigger_001.addOutputs([_Branch_003]);
		_Branch_003.addInput(_OnVolumeTrigger_001, 0);
		_Branch_003.addInput(_GetProperty_006, 0);
		_Branch_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_007 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_007.addInput(_Branch_003, 1);
		_SetProperty_007.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_SetProperty_007.addInput(_GetProperty_006, 1);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _SetProperty_006 = new armory.logicnode.SetPropertyNode(this);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Equal";
		_Gate_001.property1 = 9.999999747378752e-05;
		_Gate_001.addInput(_Sequence_001, 1);
		var _GetProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_003.addInput(_Self, 0);
		_GetProperty_003.addInput(new armory.logicnode.StringNode(this, "Group"), 0);
		var _GetProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_004.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_GetProperty_004.addInput(_GetProperty_003, 0);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Add";
		_Math.property1 = "false";
		_Math.addInput(_GetProperty_004, 0);
		_Math.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		var _SetProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_003.addInput(_Sequence_001, 4);
		_SetProperty_003.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_003.addInput(_GetProperty_004, 1);
		_SetProperty_003.addInput(_Math, 0);
		_SetProperty_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Math.addOutputs([_SetProperty_003]);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Add";
		_Math_001.property1 = "false";
		_Math_001.addInput(_GetProperty_004, 0);
		_Math_001.addInput(new armory.logicnode.FloatNode(this, -1.0), 0);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_001.addInput(_Branch_001, 0);
		_SetProperty_001.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_001.addInput(_GetProperty_004, 1);
		_SetProperty_001.addInput(_Math_001, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Math_001.addOutputs([_SetProperty_001]);
		_GetProperty_004.addOutputs([_Math, _Math_001]);
		_GetProperty_004.addOutputs([_SetProperty_003, _SetProperty_001]);
		var _SetProperty_004 = new armory.logicnode.SetPropertyNode(this);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Equal";
		_Gate.property1 = 9.999999747378752e-05;
		var _OnContact_001 = new armory.logicnode.OnContactNode(this);
		_OnContact_001.property0 = "Begin";
		_OnContact_001.addInput(_Self, 0);
		_OnContact_001.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_OnContact_001.addOutputs([_Gate]);
		_Gate.addInput(_OnContact_001, 0);
		var _GetProperty_005 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_005.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_GetProperty_005.addInput(new armory.logicnode.StringNode(this, "FirstContact"), 0);
		_GetProperty_005.addOutputs([_Gate]);
		_GetProperty_005.addOutputs([_SetProperty_004]);
		_Gate.addInput(_GetProperty_005, 0);
		var _String = new armory.logicnode.StringNode(this);
		_String.addInput(new armory.logicnode.StringNode(this, "None"), 0);
		_String.addOutputs([_Gate]);
		_Gate.addInput(_String, 0);
		_Gate.addOutputs([_SetProperty_004]);
		_Gate.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetProperty_004.addInput(_Gate, 0);
		_SetProperty_004.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_004.addInput(_GetProperty_005, 1);
		_SetProperty_004.addInput(_GetProperty_003, 0);
		_SetProperty_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_003.addOutputs([_GetProperty_004, _SetProperty_004, _Gate_001]);
		_GetProperty_003.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate_001.addInput(_GetProperty_003, 0);
		var _String_001 = new armory.logicnode.StringNode(this);
		_String_001.addInput(new armory.logicnode.StringNode(this, "Solids"), 0);
		_String_001.addOutputs([_Gate_001]);
		_Gate_001.addInput(_String_001, 0);
		var _SetProperty_005 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_005.addInput(_Gate_001, 0);
		_SetProperty_005.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_005.addInput(new armory.logicnode.StringNode(this, "SolidOnPocket"), 0);
		_SetProperty_005.addInput(_Boolean, 0);
		_SetProperty_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_001.addOutputs([_SetProperty_005]);
		_Gate_001.addOutputs([_SetProperty_006]);
		_SetProperty_006.addInput(_Gate_001, 1);
		_SetProperty_006.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_006.addInput(new armory.logicnode.StringNode(this, "StripedOnPocket"), 0);
		_SetProperty_006.addInput(_Boolean, 0);
		_SetProperty_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_Boolean.addOutputs([_SetProperty, _SetProperty_006, _SetProperty_005, _SetProperty_007]);
		_SetProperty_007.addInput(_Boolean, 0);
		_SetProperty_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_003.addOutputs([_SetProperty_007]);
		_GetProperty_006.addOutputs([_Branch_003, _Branch_005]);
		_GetProperty_006.addOutputs([_SetProperty_007, _SetProperty_008]);
		_Branch_005.addInput(_GetProperty_006, 0);
		_Branch_005.addOutputs([_SetProperty_008]);
		_Branch_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetProperty_008.addInput(_Branch_005, 0);
		_SetProperty_008.addInput(new armory.logicnode.ObjectNode(this, "Rearm"), 0);
		_SetProperty_008.addInput(_GetProperty_006, 1);
		_SetProperty_008.addInput(_Boolean_001, 0);
		_SetProperty_008.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_009 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_SetProperty_009]);
		_SetProperty_009.addInput(_OnInit, 0);
		_SetProperty_009.addInput(_Self, 0);
		_SetProperty_009.addInput(_GetProperty_001, 1);
		_SetProperty_009.addInput(_Boolean_001, 0);
		_SetProperty_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_Boolean_001.addOutputs([_SetProperty_002, _SetProperty_008, _SetProperty_009]);
		_SetProperty_002.addInput(_Boolean_001, 0);
		_SetProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_001.addOutputs([_SetProperty_002, _SetProperty_009]);
		_Branch_001.addInput(_GetProperty_001, 0);
		_Branch_001.addOutputs([_SetProperty_001]);
		_Branch_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_002.addOutputs([_Branch_001]);
		_Sequence_002.addOutputs([_SetProperty_002]);
		_Sequence_002.addOutputs([_SetLocation]);
		var _SetVisible_001 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_001.addInput(_Sequence_002, 3);
		_SetVisible_001.addInput(_Self, 0);
		_SetVisible_001.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetVisible_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_002.addOutputs([_SetVisible_001]);
		_SetLocation.addInput(_Sequence_002, 2);
		_SetLocation.addInput(_Self, 0);
		_SetLocation.addInput(_GetLocation, 0);
		_SetLocation.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetLocation.addOutputs([_SetLocation]);
		_GetObject.addOutputs([_GetLocation, _SetLocation_001]);
		_GetProperty.addOutputs([_GetObject]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _SetVisible = new armory.logicnode.SetVisibleNode(this);
		_SetVisible.addInput(_Sequence_001, 3);
		_SetVisible.addInput(_Self, 0);
		_SetVisible.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVelocity_001 = new armory.logicnode.SetVelocityNode(this);
		var _OnEvent_002 = new armory.logicnode.OnEventNode(this);
		_OnEvent_002.property0 = "RemovePhysics";
		_OnEvent_002.addOutputs([_SetVelocity_001]);
		_SetVelocity_001.addInput(_OnEvent_002, 0);
		_SetVelocity_001.addInput(_Self, 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVelocity = new armory.logicnode.SetVelocityNode(this);
		var _OnEvent_003 = new armory.logicnode.OnEventNode(this);
		_OnEvent_003.property0 = "RestorePhysics";
		_OnEvent_003.addOutputs([_SetVelocity]);
		_SetVelocity.addInput(_OnEvent_003, 0);
		_SetVelocity.addInput(_Self, 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addOutputs([new armory.logicnode.NullNode(this)]);
		_Self.addOutputs([_OnContact, _SetProperty, _GetProperty, _GetProperty_001, _SetProperty_002, _SetLocation, _GetLocation_001, _SetVisible, _SetVisible_001, _GetProperty_003, _OnContact_001, _OnVolumeTrigger, _OnVolumeTrigger_001, _RemoveObject, _SetProperty_009, _SetVelocity_001, _SetVelocity]);
		_OnContact.addInput(_Self, 0);
		_OnContact.addInput(new armory.logicnode.ObjectNode(this, "TriggerPocket"), 0);
		_OnContact.addOutputs([_Sequence_001]);
		_Sequence_001.addInput(_OnContact, 0);
		_Sequence_001.addOutputs([_SetProperty]);
		_Sequence_001.addOutputs([_Gate_001]);
		_Sequence_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_001.addOutputs([_SetVisible]);
		_Sequence_001.addOutputs([_SetProperty_003]);
		_SetProperty.addInput(_Sequence_001, 0);
		_SetProperty.addInput(_Self, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "OnPocket"), 0);
		_SetProperty.addInput(_Boolean, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}