package phfa.node;

@:keep class MainMenu extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _Shutdown = new armory.logicnode.ShutdownNode(this);
		var _Sequence_018 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_008 = new armory.logicnode.OnEventNode(this);
		_OnEvent_008.property0 = "QuitGameConfirm";
		_OnEvent_008.addOutputs([_Sequence_018]);
		_Sequence_018.addInput(_OnEvent_008, 0);
		var _Merge_009 = new armory.logicnode.MergeNode(this);
		_Merge_009.addInput(_Sequence_018, 0);
		var _Sequence_019 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_009 = new armory.logicnode.OnEventNode(this);
		_OnEvent_009.property0 = "QuitGameCancel";
		_OnEvent_009.addOutputs([_Sequence_019]);
		_Sequence_019.addInput(_OnEvent_009, 0);
		_Sequence_019.addOutputs([_Merge_009]);
		var _Merge_007 = new armory.logicnode.MergeNode(this);
		var _Sequence_012 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_005 = new armory.logicnode.OnEventNode(this);
		_OnEvent_005.property0 = "MainMenu";
		_OnEvent_005.addOutputs([_Sequence_012]);
		_Sequence_012.addInput(_OnEvent_005, 0);
		var _Merge_002 = new armory.logicnode.MergeNode(this);
		var _Sequence_004 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "2Players";
		_OnEvent_001.addOutputs([_Sequence_004]);
		_Sequence_004.addInput(_OnEvent_001, 0);
		_Sequence_004.addOutputs([_Merge_002]);
		var _Merge_003 = new armory.logicnode.MergeNode(this);
		_Merge_003.addInput(_Sequence_004, 1);
		var _Sequence_010 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_004 = new armory.logicnode.OnEventNode(this);
		_OnEvent_004.property0 = "PoolCancel";
		_OnEvent_004.addOutputs([_Sequence_010]);
		_Sequence_010.addInput(_OnEvent_004, 0);
		var _Merge_006 = new armory.logicnode.MergeNode(this);
		var _Sequence_011 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_003 = new armory.logicnode.OnEventNode(this);
		_OnEvent_003.property0 = "PoolConfirm";
		_OnEvent_003.addOutputs([_Sequence_011]);
		_Sequence_011.addInput(_OnEvent_003, 0);
		_Sequence_011.addOutputs([_Merge_006]);
		var _SetScene = new armory.logicnode.SetSceneNode(this);
		_SetScene.addInput(_Sequence_011, 1);
		var _Scene = new armory.logicnode.SceneNode(this);
		_Scene.property0 = "Pool";
		_Scene.addOutputs([_SetScene]);
		_SetScene.addInput(_Scene, 0);
		_SetScene.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetScene.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		_Sequence_011.addOutputs([_SetScene]);
		_Merge_006.addInput(_Sequence_011, 0);
		_Merge_006.addInput(_Sequence_010, 0);
		var _Sequence_009 = new armory.logicnode.SequenceNode(this);
		_Sequence_009.addInput(_Merge_006, 0);
		var _CanvasSetVisible_013 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_013.addInput(_Sequence_009, 0);
		_CanvasSetVisible_013.addInput(new armory.logicnode.StringNode(this, "PoolConfirm"), 0);
		_CanvasSetVisible_013.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_013.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_009.addOutputs([_CanvasSetVisible_013]);
		var _CanvasSetVisible_012 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_012.addInput(_Sequence_009, 1);
		_CanvasSetVisible_012.addInput(new armory.logicnode.StringNode(this, "PoolCancel"), 0);
		_CanvasSetVisible_012.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_012.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_009.addOutputs([_CanvasSetVisible_012]);
		_Merge_006.addOutputs([_Sequence_009]);
		_Sequence_010.addOutputs([_Merge_006]);
		_Sequence_010.addOutputs([_Merge_003]);
		_Merge_003.addInput(_Sequence_010, 1);
		var _Sequence_005 = new armory.logicnode.SequenceNode(this);
		_Sequence_005.addInput(_Merge_003, 0);
		var _CanvasSetVisible_006 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_006.addInput(_Sequence_005, 0);
		_CanvasSetVisible_006.addInput(new armory.logicnode.StringNode(this, "Pool"), 0);
		_CanvasSetVisible_006.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_004 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_004.addInput(_CanvasSetVisible_006, 0);
		_CanvasSetText_004.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetText_004.addInput(new armory.logicnode.StringNode(this, "2 players"), 0);
		_CanvasSetText_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_006.addOutputs([_CanvasSetText_004]);
		_Sequence_005.addOutputs([_CanvasSetVisible_006]);
		var _CanvasSetVisible_007 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_007.addInput(_Sequence_005, 1);
		_CanvasSetVisible_007.addInput(new armory.logicnode.StringNode(this, "BackToStartGame"), 0);
		_CanvasSetVisible_007.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_005 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_005.addInput(_CanvasSetVisible_007, 0);
		_CanvasSetText_005.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetText_005.addInput(new armory.logicnode.StringNode(this, "Select a game style"), 0);
		_CanvasSetText_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_007.addOutputs([_CanvasSetText_005]);
		_Sequence_005.addOutputs([_CanvasSetVisible_007]);
		_Merge_003.addOutputs([_Sequence_005]);
		_Sequence_004.addOutputs([_Merge_003]);
		_Merge_002.addInput(_Sequence_004, 0);
		_Merge_002.addInput(_Sequence_012, 0);
		var _Sequence_003 = new armory.logicnode.SequenceNode(this);
		_Sequence_003.addInput(_Merge_002, 0);
		var _CanvasSetVisible_004 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_004.addInput(_Sequence_003, 0);
		_CanvasSetVisible_004.addInput(new armory.logicnode.StringNode(this, "2Players"), 0);
		_CanvasSetVisible_004.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_003.addOutputs([_CanvasSetVisible_004]);
		var _CanvasSetVisible_005 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_005.addInput(_Sequence_003, 1);
		_CanvasSetVisible_005.addInput(new armory.logicnode.StringNode(this, "MainMenu"), 0);
		_CanvasSetVisible_005.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_003.addOutputs([_CanvasSetVisible_005]);
		_Merge_002.addOutputs([_Sequence_003]);
		_Sequence_012.addOutputs([_Merge_002]);
		_Sequence_012.addOutputs([_Merge_007]);
		_Merge_007.addInput(_Sequence_012, 1);
		_Merge_007.addInput(_Sequence_019, 1);
		var _Sequence_013 = new armory.logicnode.SequenceNode(this);
		_Sequence_013.addInput(_Merge_007, 0);
		var _CanvasSetVisible_014 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_014.addInput(_Sequence_013, 0);
		_CanvasSetVisible_014.addInput(new armory.logicnode.StringNode(this, "StartGame"), 0);
		_CanvasSetVisible_014.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText.addInput(_CanvasSetVisible_014, 0);
		_CanvasSetText.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetText.addInput(new armory.logicnode.StringNode(this, "Simple Pool"), 0);
		_CanvasSetText.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_014.addOutputs([_CanvasSetText]);
		_Sequence_013.addOutputs([_CanvasSetVisible_014]);
		var _CanvasSetVisible_015 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_015.addInput(_Sequence_013, 1);
		_CanvasSetVisible_015.addInput(new armory.logicnode.StringNode(this, "QuitGame"), 0);
		_CanvasSetVisible_015.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_001 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_001.addInput(_CanvasSetVisible_015, 0);
		_CanvasSetText_001.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetText_001.addInput(new armory.logicnode.StringNode(this, "Welcome!"), 0);
		_CanvasSetText_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_015.addOutputs([_CanvasSetText_001]);
		_Sequence_013.addOutputs([_CanvasSetVisible_015]);
		_Merge_007.addOutputs([_Sequence_013]);
		_Sequence_019.addOutputs([_Merge_007]);
		_Merge_009.addInput(_Sequence_019, 0);
		var _Sequence_017 = new armory.logicnode.SequenceNode(this);
		_Sequence_017.addInput(_Merge_009, 0);
		var _CanvasSetVisible_018 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_018.addInput(_Sequence_017, 0);
		_CanvasSetVisible_018.addInput(new armory.logicnode.StringNode(this, "QuitGameConfirm"), 0);
		_CanvasSetVisible_018.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_018.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_017.addOutputs([_CanvasSetVisible_018]);
		var _CanvasSetVisible_019 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_019.addInput(_Sequence_017, 1);
		_CanvasSetVisible_019.addInput(new armory.logicnode.StringNode(this, "QuitGameCancel"), 0);
		_CanvasSetVisible_019.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_019.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_017.addOutputs([_CanvasSetVisible_019]);
		_Merge_009.addOutputs([_Sequence_017]);
		_Sequence_018.addOutputs([_Merge_009]);
		_Sequence_018.addOutputs([_Shutdown]);
		_Shutdown.addInput(_Sequence_018, 1);
		_Shutdown.addOutputs([new armory.logicnode.NullNode(this)]);
		var _CanvasSetVisible_001 = new armory.logicnode.CanvasSetVisibleNode(this);
		var _Sequence = new armory.logicnode.SequenceNode(this);
		var _Merge = new armory.logicnode.MergeNode(this);
		var _Sequence_001 = new armory.logicnode.SequenceNode(this);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "StartGame";
		_OnEvent.addOutputs([_Sequence_001]);
		_Sequence_001.addInput(_OnEvent, 0);
		_Sequence_001.addOutputs([_Merge]);
		var _Merge_001 = new armory.logicnode.MergeNode(this);
		_Merge_001.addInput(_Sequence_001, 1);
		var _Sequence_014 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_006 = new armory.logicnode.OnEventNode(this);
		_OnEvent_006.property0 = "BackToStartGame";
		_OnEvent_006.addOutputs([_Sequence_014]);
		_Sequence_014.addInput(_OnEvent_006, 0);
		var _Merge_004 = new armory.logicnode.MergeNode(this);
		var _Sequence_007 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_002 = new armory.logicnode.OnEventNode(this);
		_OnEvent_002.property0 = "Pool";
		_OnEvent_002.addOutputs([_Sequence_007]);
		_Sequence_007.addInput(_OnEvent_002, 0);
		_Sequence_007.addOutputs([_Merge_004]);
		var _Merge_005 = new armory.logicnode.MergeNode(this);
		_Merge_005.addInput(_Sequence_007, 1);
		var _Sequence_008 = new armory.logicnode.SequenceNode(this);
		_Sequence_008.addInput(_Merge_005, 0);
		var _CanvasSetVisible_011 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_011.addInput(_Sequence_008, 0);
		_CanvasSetVisible_011.addInput(new armory.logicnode.StringNode(this, "PoolConfirm"), 0);
		_CanvasSetVisible_011.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_006 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_006.addInput(_CanvasSetVisible_011, 0);
		_CanvasSetText_006.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetText_006.addInput(new armory.logicnode.StringNode(this, "2 players > Solids and Stripes"), 0);
		_CanvasSetText_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_011.addOutputs([_CanvasSetText_006]);
		_Sequence_008.addOutputs([_CanvasSetVisible_011]);
		var _CanvasSetVisible_010 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_010.addInput(_Sequence_008, 1);
		_CanvasSetVisible_010.addInput(new armory.logicnode.StringNode(this, "PoolCancel"), 0);
		_CanvasSetVisible_010.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_007 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_007.addInput(_CanvasSetVisible_010, 0);
		_CanvasSetText_007.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetText_007.addInput(new armory.logicnode.StringNode(this, "Are you sure?"), 0);
		_CanvasSetText_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_010.addOutputs([_CanvasSetText_007]);
		_Sequence_008.addOutputs([_CanvasSetVisible_010]);
		_Merge_005.addOutputs([_Sequence_008]);
		_Sequence_007.addOutputs([_Merge_005]);
		_Merge_004.addInput(_Sequence_007, 0);
		_Merge_004.addInput(_Sequence_014, 0);
		var _Sequence_006 = new armory.logicnode.SequenceNode(this);
		_Sequence_006.addInput(_Merge_004, 0);
		var _CanvasSetVisible_009 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_009.addInput(_Sequence_006, 0);
		_CanvasSetVisible_009.addInput(new armory.logicnode.StringNode(this, "Pool"), 0);
		_CanvasSetVisible_009.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_006.addOutputs([_CanvasSetVisible_009]);
		var _CanvasSetVisible_008 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_008.addInput(_Sequence_006, 1);
		_CanvasSetVisible_008.addInput(new armory.logicnode.StringNode(this, "BackToStartGame"), 0);
		_CanvasSetVisible_008.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_008.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_006.addOutputs([_CanvasSetVisible_008]);
		_Merge_004.addOutputs([_Sequence_006]);
		_Sequence_014.addOutputs([_Merge_004]);
		_Sequence_014.addOutputs([_Merge_001]);
		_Merge_001.addInput(_Sequence_014, 1);
		var _Sequence_002 = new armory.logicnode.SequenceNode(this);
		_Sequence_002.addInput(_Merge_001, 0);
		var _CanvasSetVisible_002 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_002.addInput(_Sequence_002, 0);
		_CanvasSetVisible_002.addInput(new armory.logicnode.StringNode(this, "2Players"), 0);
		_CanvasSetVisible_002.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_002 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_002.addInput(_CanvasSetVisible_002, 0);
		_CanvasSetText_002.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetText_002.addInput(new armory.logicnode.StringNode(this, "Start"), 0);
		_CanvasSetText_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_002.addOutputs([_CanvasSetText_002]);
		_Sequence_002.addOutputs([_CanvasSetVisible_002]);
		var _CanvasSetVisible_003 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_003.addInput(_Sequence_002, 1);
		_CanvasSetVisible_003.addInput(new armory.logicnode.StringNode(this, "MainMenu"), 0);
		_CanvasSetVisible_003.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_003 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_003.addInput(_CanvasSetVisible_003, 0);
		_CanvasSetText_003.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetText_003.addInput(new armory.logicnode.StringNode(this, "Select a mode"), 0);
		_CanvasSetText_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_003.addOutputs([_CanvasSetText_003]);
		_Sequence_002.addOutputs([_CanvasSetVisible_003]);
		_Merge_001.addOutputs([_Sequence_002]);
		_Sequence_001.addOutputs([_Merge_001]);
		_Merge.addInput(_Sequence_001, 0);
		var _Sequence_015 = new armory.logicnode.SequenceNode(this);
		var _OnEvent_007 = new armory.logicnode.OnEventNode(this);
		_OnEvent_007.property0 = "QuitGame";
		_OnEvent_007.addOutputs([_Sequence_015]);
		_Sequence_015.addInput(_OnEvent_007, 0);
		_Sequence_015.addOutputs([_Merge]);
		var _Merge_008 = new armory.logicnode.MergeNode(this);
		_Merge_008.addInput(_Sequence_015, 1);
		var _Sequence_016 = new armory.logicnode.SequenceNode(this);
		_Sequence_016.addInput(_Merge_008, 0);
		var _CanvasSetVisible_016 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_016.addInput(_Sequence_016, 0);
		_CanvasSetVisible_016.addInput(new armory.logicnode.StringNode(this, "QuitGameConfirm"), 0);
		_CanvasSetVisible_016.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_008 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_008.addInput(_CanvasSetVisible_016, 0);
		_CanvasSetText_008.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetText_008.addInput(new armory.logicnode.StringNode(this, "Exit"), 0);
		_CanvasSetText_008.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_016.addOutputs([_CanvasSetText_008]);
		_Sequence_016.addOutputs([_CanvasSetVisible_016]);
		var _CanvasSetVisible_017 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_017.addInput(_Sequence_016, 1);
		_CanvasSetVisible_017.addInput(new armory.logicnode.StringNode(this, "QuitGameCancel"), 0);
		_CanvasSetVisible_017.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetText_009 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_009.addInput(_CanvasSetVisible_017, 0);
		_CanvasSetText_009.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetText_009.addInput(new armory.logicnode.StringNode(this, "Are you sure?"), 0);
		_CanvasSetText_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_017.addOutputs([_CanvasSetText_009]);
		_Sequence_016.addOutputs([_CanvasSetVisible_017]);
		_Merge_008.addOutputs([_Sequence_016]);
		_Sequence_015.addOutputs([_Merge_008]);
		_Merge.addInput(_Sequence_015, 0);
		_Merge.addOutputs([_Sequence]);
		_Sequence.addInput(_Merge, 0);
		var _CanvasSetVisible = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible.addInput(_Sequence, 0);
		_CanvasSetVisible.addInput(new armory.logicnode.StringNode(this, "StartGame"), 0);
		_CanvasSetVisible.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_CanvasSetVisible]);
		_Sequence.addOutputs([_CanvasSetVisible_001]);
		_CanvasSetVisible_001.addInput(_Sequence, 1);
		_CanvasSetVisible_001.addInput(new armory.logicnode.StringNode(this, "QuitGame"), 0);
		_CanvasSetVisible_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _CanvasSetScale_005 = new armory.logicnode.CanvasSetScaleNode(this);
		var _Sequence_020 = new armory.logicnode.SequenceNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_Sequence_020]);
		_Sequence_020.addInput(_OnInit, 0);
		var _CanvasSetScale_003 = new armory.logicnode.CanvasSetScaleNode(this);
		_CanvasSetScale_003.addInput(_Sequence_020, 0);
		_CanvasSetScale_003.addInput(new armory.logicnode.StringNode(this, "Title"), 0);
		_CanvasSetScale_003.addInput(new armory.logicnode.IntegerNode(this, 96), 0);
		var _DisplayInfo_001 = new armory.logicnode.DisplayInfoNode(this);
		var _CanvasSetScale_004 = new armory.logicnode.CanvasSetScaleNode(this);
		_CanvasSetScale_004.addInput(_Sequence_020, 1);
		_CanvasSetScale_004.addInput(new armory.logicnode.StringNode(this, "Subtitle"), 0);
		_CanvasSetScale_004.addInput(new armory.logicnode.IntegerNode(this, 48), 0);
		_CanvasSetScale_004.addInput(_DisplayInfo_001, 0);
		_CanvasSetScale_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_DisplayInfo_001.addOutputs([_CanvasSetScale_003, _CanvasSetScale_004, _CanvasSetScale_005]);
		_DisplayInfo_001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_CanvasSetScale_003.addInput(_DisplayInfo_001, 0);
		_CanvasSetScale_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_020.addOutputs([_CanvasSetScale_003]);
		_Sequence_020.addOutputs([_CanvasSetScale_004]);
		_Sequence_020.addOutputs([_CanvasSetScale_005]);
		_CanvasSetScale_005.addInput(_Sequence_020, 2);
		_CanvasSetScale_005.addInput(new armory.logicnode.StringNode(this, "Version"), 0);
		_CanvasSetScale_005.addInput(new armory.logicnode.IntegerNode(this, 24), 0);
		_CanvasSetScale_005.addInput(_DisplayInfo_001, 0);
		_CanvasSetScale_005.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}