package phfa.node;

@:keep class Rearm extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetProperty_007 = new armory.logicnode.SetPropertyNode(this);
		var _Sequence = new armory.logicnode.SequenceNode(this);
		var _Merge_004 = new armory.logicnode.MergeNode(this);
		var _Branch_007 = new armory.logicnode.BranchNode(this);
		var _Branch_006 = new armory.logicnode.BranchNode(this);
		var _OnCanvasElement = new armory.logicnode.OnCanvasElementNode(this);
		_OnCanvasElement.property0 = "click";
		_OnCanvasElement.property1 = "started";
		_OnCanvasElement.property2 = "left";
		_OnCanvasElement.addInput(new armory.logicnode.StringNode(this, "Rearm"), 0);
		_OnCanvasElement.addOutputs([_Branch_006]);
		_Branch_006.addInput(_OnCanvasElement, 0);
		var _GetProperty_005 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_005.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_GetProperty_005.addInput(new armory.logicnode.StringNode(this, "LockScene"), 0);
		_GetProperty_005.addOutputs([_Branch_006]);
		var _SetProperty_008 = new armory.logicnode.SetPropertyNode(this);
		var _Sequence_001 = new armory.logicnode.SequenceNode(this);
		var _Branch_005 = new armory.logicnode.BranchNode(this);
		var _Merge_002 = new armory.logicnode.MergeNode(this);
		var _Branch_003 = new armory.logicnode.BranchNode(this);
		var _Branch_002 = new armory.logicnode.BranchNode(this);
		var _Branch_001 = new armory.logicnode.BranchNode(this);
		var _OnSurface_001 = new armory.logicnode.OnSurfaceNode(this);
		_OnSurface_001.property0 = "Released";
		_OnSurface_001.addOutputs([_Branch_001]);
		_Branch_001.addInput(_OnSurface_001, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		var _Self = new armory.logicnode.SelfNode(this);
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		var _Merge_001 = new armory.logicnode.MergeNode(this);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Greater";
		_Gate.property1 = 9.999999747378752e-05;
		var _Branch = new armory.logicnode.BranchNode(this);
		var _OnSurface = new armory.logicnode.OnSurfaceNode(this);
		_OnSurface.property0 = "Moved";
		_OnSurface.addOutputs([_Branch]);
		_Branch.addInput(_OnSurface, 0);
		_Branch.addInput(_GetProperty, 0);
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Less";
		_Gate_003.property1 = 9.999999747378752e-05;
		_Gate_003.addInput(_Branch, 0);
		var _SeparateXYZ = new armory.logicnode.SeparateVectorNode(this);
		var _SurfaceCoords = new armory.logicnode.SurfaceCoordsNode(this);
		_SurfaceCoords.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_SurfaceCoords.addOutputs([_SeparateXYZ]);
		_SeparateXYZ.addInput(_SurfaceCoords, 1);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Multiply";
		_Math_001.property1 = "false";
		_Math_001.addInput(_SeparateXYZ, 0);
		_Math_001.addInput(new armory.logicnode.FloatNode(this, 0.02500000037252903), 0);
		var _Vector = new armory.logicnode.VectorNode(this);
		_Vector.addInput(_Math_001, 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addOutputs([_TranslateObject]);
		_Math_001.addOutputs([_Vector]);
		_SeparateXYZ.addOutputs([_Math_001, _Gate, _Gate_003]);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Multiply";
		_Math.property1 = "false";
		_Math.addInput(_SeparateXYZ, 1);
		_Math.addInput(new armory.logicnode.FloatNode(this, -0.02500000037252903), 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_001.addInput(_Math, 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _TranslateObject_002 = new armory.logicnode.TranslateObjectNode(this);
		var _Merge = new armory.logicnode.MergeNode(this);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Less";
		_Gate_002.property1 = 9.999999747378752e-05;
		_Gate_002.addInput(_Branch, 0);
		_Gate_002.addInput(_SeparateXYZ, 1);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Greater";
		_Gate_001.property1 = 9.999999747378752e-05;
		_Gate_001.addInput(_Branch, 0);
		_Gate_001.addInput(_SeparateXYZ, 1);
		_Gate_001.addInput(_Float, 0);
		_Gate_001.addOutputs([_Merge]);
		_Gate_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Float.addOutputs([_Gate, _Gate_001, _Gate_003, _Gate_002]);
		_Gate_002.addInput(_Float, 0);
		_Gate_002.addOutputs([_Merge]);
		_Gate_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Merge.addInput(_Gate_002, 0);
		_Merge.addInput(_Gate_001, 0);
		_Merge.addOutputs([_TranslateObject_002]);
		_TranslateObject_002.addInput(_Merge, 0);
		_TranslateObject_002.addInput(_Self, 0);
		_TranslateObject_002.addInput(_Vector_001, 0);
		_TranslateObject_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _Merge_009 = new armory.logicnode.MergeNode(this);
		_Merge_009.addInput(_TranslateObject, 0);
		_Merge_009.addInput(_TranslateObject_002, 0);
		_Merge_009.addInput(_Sequence, 6);
		var _Sequence_003 = new armory.logicnode.SequenceNode(this);
		var _Branch_011 = new armory.logicnode.BranchNode(this);
		var _Merge_005 = new armory.logicnode.MergeNode(this);
		var _Branch_009 = new armory.logicnode.BranchNode(this);
		_Branch_009.addInput(_Branch, 0);
		var _GetProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_003.addInput(_Self, 0);
		_GetProperty_003.addInput(new armory.logicnode.StringNode(this, "LimitedToTheKitchen"), 0);
		_GetProperty_003.addOutputs([_Branch_002, _Branch_009]);
		_GetProperty_003.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Branch_009.addInput(_GetProperty_003, 0);
		_Branch_009.addOutputs([_Merge_005]);
		var _Merge_008 = new armory.logicnode.MergeNode(this);
		_Merge_008.addInput(_Branch_009, 1);
		var _Branch_004 = new armory.logicnode.BranchNode(this);
		_Branch_004.addInput(_Branch_002, 1);
		var _GetProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_002.addInput(_Self, 0);
		_GetProperty_002.addInput(new armory.logicnode.StringNode(this, "TriggerPlayField"), 0);
		var _Branch_010 = new armory.logicnode.BranchNode(this);
		_Branch_010.addInput(_Merge_008, 0);
		_Branch_010.addInput(_GetProperty_002, 0);
		_Branch_010.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Sequence_002 = new armory.logicnode.SequenceNode(this);
		_Sequence_002.addInput(_Branch_010, 1);
		var _SetLocation_003 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_003.addInput(_Sequence_002, 0);
		_SetLocation_003.addInput(_Self, 0);
		var _GetLocation_004 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_004.addInput(new armory.logicnode.ObjectNode(this, "TriggerPlayField"), 0);
		_GetLocation_004.addOutputs([_SetLocation_003]);
		_SetLocation_003.addInput(_GetLocation_004, 0);
		_SetLocation_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_002.addOutputs([_SetLocation_003]);
		_Sequence_002.addOutputs([_Merge_009]);
		var _Merge_007 = new armory.logicnode.MergeNode(this);
		var _OnVolumeTrigger_001 = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger_001.property0 = "Enter";
		_OnVolumeTrigger_001.addInput(_Self, 0);
		_OnVolumeTrigger_001.addInput(new armory.logicnode.ObjectNode(this, "TriggerPlayField"), 0);
		_OnVolumeTrigger_001.addOutputs([_Merge_007]);
		_Merge_007.addInput(_OnVolumeTrigger_001, 0);
		_Merge_007.addInput(_Sequence_002, 2);
		var _SetProperty_005 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_005.addInput(_Merge_007, 0);
		_SetProperty_005.addInput(_Self, 0);
		_SetProperty_005.addInput(_GetProperty_002, 1);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		_SetProperty.addInput(_Sequence, 7);
		_SetProperty.addInput(_Self, 0);
		_SetProperty.addInput(_GetProperty, 1);
		_SetProperty.addInput(_Boolean, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_004 = new armory.logicnode.SetPropertyNode(this);
		var _Merge_006 = new armory.logicnode.MergeNode(this);
		var _OnVolumeTrigger = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger.property0 = "Enter";
		_OnVolumeTrigger.addInput(_Self, 0);
		_OnVolumeTrigger.addInput(new armory.logicnode.ObjectNode(this, "TriggerTheKitchen"), 0);
		_OnVolumeTrigger.addOutputs([_Merge_006]);
		_Merge_006.addInput(_OnVolumeTrigger, 0);
		_Merge_006.addInput(_Sequence_003, 2);
		_Merge_006.addOutputs([_SetProperty_004]);
		_SetProperty_004.addInput(_Merge_006, 0);
		_SetProperty_004.addInput(_Self, 0);
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_001.addInput(_Self, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "TriggerTheKitchen"), 0);
		_GetProperty_001.addOutputs([_Branch_003, _Branch_011]);
		var _SetProperty_002 = new armory.logicnode.SetPropertyNode(this);
		var _OnVolumeTrigger_002 = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger_002.property0 = "Leave";
		_OnVolumeTrigger_002.addInput(_Self, 0);
		_OnVolumeTrigger_002.addInput(new armory.logicnode.ObjectNode(this, "TriggerTheKitchen"), 0);
		_OnVolumeTrigger_002.addOutputs([_SetProperty_002]);
		_SetProperty_002.addInput(_OnVolumeTrigger_002, 0);
		_SetProperty_002.addInput(_Self, 0);
		_SetProperty_002.addInput(_GetProperty_001, 1);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_001.addInput(_Sequence, 2);
		_SetProperty_001.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "ShotAllowed"), 0);
		_SetProperty_001.addInput(_Boolean_001, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_003 = new armory.logicnode.SetPropertyNode(this);
		var _OnVolumeTrigger_003 = new armory.logicnode.OnVolumeTriggerNode(this);
		_OnVolumeTrigger_003.property0 = "Leave";
		_OnVolumeTrigger_003.addInput(_Self, 0);
		_OnVolumeTrigger_003.addInput(new armory.logicnode.ObjectNode(this, "TriggerPlayField"), 0);
		_OnVolumeTrigger_003.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_OnVolumeTrigger_003, 0);
		_SetProperty_003.addInput(_Self, 0);
		_SetProperty_003.addInput(_GetProperty_002, 1);
		_SetProperty_003.addInput(_Boolean_001, 0);
		_SetProperty_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_006 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_006.addInput(_Sequence_001, 0);
		_SetProperty_006.addInput(_Self, 0);
		_SetProperty_006.addInput(_GetProperty, 1);
		_SetProperty_006.addInput(_Boolean_001, 0);
		_SetProperty_006.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_010 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_010.addInput(_Sequence_001, 4);
		_SetProperty_010.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		var _GetProperty_008 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_008.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_GetProperty_008.addInput(new armory.logicnode.StringNode(this, "OnPocket"), 0);
		var _Branch_008 = new armory.logicnode.BranchNode(this);
		_Branch_008.addInput(_Sequence_001, 3);
		_Branch_008.addInput(_GetProperty_008, 0);
		_Branch_008.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_001.addInput(_Branch_008, 1);
		_SetLocation_001.addInput(new armory.logicnode.ObjectNode(this, "WhiteLocal"), 0);
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_001.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_GetLocation_001.addOutputs([_SetLocation_001]);
		_SetLocation_001.addInput(_GetLocation_001, 0);
		_SetLocation_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_008.addOutputs([_SetLocation_001]);
		_GetProperty_008.addOutputs([_Branch_008]);
		_GetProperty_008.addOutputs([_SetProperty_010]);
		_SetProperty_010.addInput(_GetProperty_008, 1);
		_SetProperty_010.addInput(_Boolean_001, 0);
		_SetProperty_010.addOutputs([new armory.logicnode.NullNode(this)]);
		_Boolean_001.addOutputs([_SetProperty_001, _SetProperty_002, _SetProperty_003, _SetProperty_006, _SetProperty_008, _SetProperty_010]);
		_SetProperty_002.addInput(_Boolean_001, 0);
		_SetProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_001.addOutputs([_SetProperty_002, _SetProperty_004]);
		_SetProperty_004.addInput(_GetProperty_001, 1);
		_SetProperty_004.addInput(_Boolean, 0);
		_SetProperty_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_009 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_009.addInput(_Sequence_001, 1);
		_SetProperty_009.addInput(_Self, 0);
		var _GetProperty_006 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_006.addInput(_Self, 0);
		_GetProperty_006.addInput(new armory.logicnode.StringNode(this, "Rearmable"), 0);
		_GetProperty_006.addOutputs([_Branch_007]);
		_GetProperty_006.addOutputs([_SetProperty_009]);
		_SetProperty_009.addInput(_GetProperty_006, 1);
		_SetProperty_009.addInput(_Boolean, 0);
		_SetProperty_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_Boolean.addOutputs([_SetProperty, _SetProperty_004, _SetProperty_005, _SetProperty_007, _SetProperty_009]);
		_SetProperty_005.addInput(_Boolean, 0);
		_SetProperty_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_Merge_007.addOutputs([_SetProperty_005]);
		_Sequence_002.addOutputs([_Merge_007]);
		_Branch_010.addOutputs([_Sequence_002]);
		_GetProperty_002.addOutputs([_Branch_004, _Branch_010]);
		_GetProperty_002.addOutputs([_SetProperty_005, _SetProperty_003]);
		_Branch_004.addInput(_GetProperty_002, 0);
		_Branch_004.addOutputs([_Merge_002]);
		var _CanvasSetText_002 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_002.addInput(_Branch_004, 1);
		_CanvasSetText_002.addInput(new armory.logicnode.StringNode(this, "Message"), 0);
		_CanvasSetText_002.addInput(new armory.logicnode.StringNode(this, "A bola pode ser colocada somente em cima da mesa!"), 0);
		var _Merge_003 = new armory.logicnode.MergeNode(this);
		var _CanvasSetText = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText.addInput(_Branch_003, 1);
		_CanvasSetText.addInput(new armory.logicnode.StringNode(this, "Message"), 0);
		_CanvasSetText.addInput(new armory.logicnode.StringNode(this, "A bola pode ser colocada somente antes da linha branca!"), 0);
		_CanvasSetText.addOutputs([_Merge_003]);
		_Merge_003.addInput(_CanvasSetText, 0);
		var _CanvasSetText_001 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_001.addInput(_Branch_005, 0);
		_CanvasSetText_001.addInput(new armory.logicnode.StringNode(this, "Message"), 0);
		_CanvasSetText_001.addInput(new armory.logicnode.StringNode(this, "A bola pode ser colocada somente em um local desocupado!"), 0);
		_CanvasSetText_001.addOutputs([_Merge_003]);
		_Merge_003.addInput(_CanvasSetText_001, 0);
		_Merge_003.addInput(_CanvasSetText_002, 0);
		var _Timer = new armory.logicnode.TimerNode(this);
		_Timer.addInput(_Merge_003, 0);
		_Timer.addInput(new armory.logicnode.NullNode(this), 0);
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "MainMenuConfirm";
		_OnEvent_001.addOutputs([_Timer]);
		_Timer.addInput(_OnEvent_001, 0);
		_Timer.addInput(new armory.logicnode.FloatNode(this, 3.0), 0);
		_Timer.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		_Timer.addOutputs([new armory.logicnode.NullNode(this)]);
		var _CanvasSetText_003 = new armory.logicnode.CanvasSetTextNode(this);
		_CanvasSetText_003.addInput(_Timer, 1);
		_CanvasSetText_003.addInput(new armory.logicnode.StringNode(this, "Message"), 0);
		_CanvasSetText_003.addInput(new armory.logicnode.StringNode(this, " "), 0);
		_CanvasSetText_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Timer.addOutputs([_CanvasSetText_003]);
		_Timer.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Timer.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Timer.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Timer.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Timer.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Merge_003.addOutputs([_Timer]);
		_CanvasSetText_002.addOutputs([_Merge_003]);
		_Branch_004.addOutputs([_CanvasSetText_002, _Merge_008]);
		_Merge_008.addInput(_Branch_004, 1);
		_Merge_008.addOutputs([_Branch_010]);
		_Branch_009.addOutputs([_Merge_008]);
		_Merge_005.addInput(_Branch_009, 0);
		_Merge_005.addInput(_Branch_003, 1);
		_Merge_005.addOutputs([_Branch_011]);
		_Branch_011.addInput(_Merge_005, 0);
		_Branch_011.addInput(_GetProperty_001, 0);
		_Branch_011.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_011.addOutputs([_Sequence_003]);
		_Sequence_003.addInput(_Branch_011, 1);
		var _SetLocation_002 = new armory.logicnode.SetLocationNode(this);
		_SetLocation_002.addInput(_Sequence_003, 0);
		_SetLocation_002.addInput(_Self, 0);
		var _GetLocation_003 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_003.addInput(new armory.logicnode.ObjectNode(this, "TriggerTheKitchen"), 0);
		_GetLocation_003.addOutputs([_SetLocation_002]);
		_SetLocation_002.addInput(_GetLocation_003, 0);
		_SetLocation_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_003.addOutputs([_SetLocation_002]);
		_Sequence_003.addOutputs([_Merge_009]);
		_Sequence_003.addOutputs([_Merge_006]);
		_Merge_009.addInput(_Sequence_003, 1);
		_Merge_009.addInput(_Sequence_002, 1);
		var _SetLocation = new armory.logicnode.SetLocationNode(this);
		_SetLocation.addInput(_Merge_009, 0);
		_SetLocation.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(_Self, 0);
		_GetLocation.addOutputs([_SetLocation]);
		_SetLocation.addInput(_GetLocation, 0);
		_SetLocation.addOutputs([new armory.logicnode.NullNode(this)]);
		_Merge_009.addOutputs([_SetLocation]);
		_TranslateObject_002.addOutputs([_Merge_009]);
		_Vector_001.addOutputs([_TranslateObject_002]);
		_Math.addOutputs([_Vector_001]);
		_SeparateXYZ.addOutputs([_Math, _Gate_002, _Gate_001]);
		_SeparateXYZ.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Gate_003.addInput(_SeparateXYZ, 0);
		_Gate_003.addInput(_Float, 0);
		_Gate_003.addOutputs([_Merge_001]);
		_Gate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch.addOutputs([_Gate, _Gate_003, _Gate_002, _Gate_001, _Branch_009]);
		_Branch.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate.addInput(_Branch, 0);
		_Gate.addInput(_SeparateXYZ, 0);
		_Gate.addInput(_Float, 0);
		_Gate.addOutputs([_Merge_001]);
		_Gate.addOutputs([new armory.logicnode.NullNode(this)]);
		_Merge_001.addInput(_Gate, 0);
		_Merge_001.addInput(_Gate_003, 0);
		_Merge_001.addOutputs([_TranslateObject]);
		_TranslateObject.addInput(_Merge_001, 0);
		_TranslateObject.addInput(_Self, 0);
		_TranslateObject.addInput(_Vector, 0);
		_TranslateObject.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject.addOutputs([_Merge_009]);
		var _GetProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_004.addInput(_Self, 0);
		_GetProperty_004.addInput(new armory.logicnode.StringNode(this, "TriggeringBall"), 0);
		_GetProperty_004.addOutputs([_Branch_005]);
		_GetProperty_004.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Self.addOutputs([_TranslateObject, _TranslateObject_002, _GetProperty, _SetProperty, _GetLocation, _OnVolumeTrigger, _OnVolumeTrigger_001, _SetProperty_004, _SetProperty_002, _SetProperty_005, _SetProperty_003, _GetProperty_001, _GetProperty_002, _OnVolumeTrigger_002, _OnVolumeTrigger_003, _GetProperty_003, _GetProperty_004, _SetProperty_006, _GetProperty_006, _SetProperty_009, _SetLocation_002, _SetLocation_003]);
		_GetProperty.addInput(_Self, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Enabled"), 0);
		_GetProperty.addOutputs([_Branch, _Branch_001]);
		_GetProperty.addOutputs([_SetProperty, _SetProperty_006]);
		_Branch_001.addInput(_GetProperty, 0);
		_Branch_001.addOutputs([_Branch_002]);
		_Branch_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_002.addInput(_Branch_001, 0);
		_Branch_002.addInput(_GetProperty_003, 0);
		_Branch_002.addOutputs([_Branch_003]);
		_Branch_002.addOutputs([_Branch_004]);
		_Branch_003.addInput(_Branch_002, 0);
		_Branch_003.addInput(_GetProperty_001, 0);
		_Branch_003.addOutputs([_Merge_002]);
		_Branch_003.addOutputs([_CanvasSetText, _Merge_005]);
		_Merge_002.addInput(_Branch_003, 0);
		_Merge_002.addInput(_Branch_004, 0);
		_Merge_002.addOutputs([_Branch_005]);
		_Branch_005.addInput(_Merge_002, 0);
		_Branch_005.addInput(_GetProperty_004, 0);
		_Branch_005.addOutputs([_CanvasSetText_001]);
		_Branch_005.addOutputs([_Sequence_001]);
		_Sequence_001.addInput(_Branch_005, 1);
		_Sequence_001.addOutputs([_SetProperty_006]);
		_Sequence_001.addOutputs([_SetProperty_009]);
		var _SendGlobalEvent_001 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_001.addInput(_Sequence_001, 2);
		_SendGlobalEvent_001.addInput(new armory.logicnode.StringNode(this, "ShowInterface"), 0);
		_SendGlobalEvent_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence_001.addOutputs([_SendGlobalEvent_001]);
		_Sequence_001.addOutputs([_Branch_008]);
		_Sequence_001.addOutputs([_SetProperty_010]);
		_Sequence_001.addOutputs([_SetProperty_008]);
		_SetProperty_008.addInput(_Sequence_001, 5);
		_SetProperty_008.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_008.addInput(_GetProperty_005, 1);
		_SetProperty_008.addInput(_Boolean_001, 0);
		_SetProperty_008.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_005.addOutputs([_SetProperty_007, _SetProperty_008]);
		_Branch_006.addInput(_GetProperty_005, 0);
		_Branch_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_006.addOutputs([_Branch_007]);
		_Branch_007.addInput(_Branch_006, 1);
		_Branch_007.addInput(_GetProperty_006, 0);
		_Branch_007.addOutputs([_Merge_004]);
		_Branch_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_Merge_004.addInput(_Branch_007, 0);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "ForceRearm";
		_OnEvent.addOutputs([_Merge_004]);
		_Merge_004.addInput(_OnEvent, 0);
		_Merge_004.addOutputs([_Sequence]);
		_Sequence.addInput(_Merge_004, 0);
		_Sequence.addOutputs([_SetProperty_007]);
		var _SendGlobalEvent_002 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_002.addInput(_Sequence, 1);
		_SendGlobalEvent_002.addInput(new armory.logicnode.StringNode(this, "HideInterface"), 0);
		_SendGlobalEvent_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SendGlobalEvent_002]);
		_Sequence.addOutputs([_SetProperty_001]);
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent.addInput(_Sequence, 3);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, "SuspendPhysics"), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SendGlobalEvent]);
		var _SetVisible_002 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_002.addInput(_Sequence, 4);
		_SetVisible_002.addInput(new armory.logicnode.ObjectNode(this, "Cue"), 0);
		_SetVisible_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SetVisible_002]);
		var _SetCamera_001 = new armory.logicnode.SetCameraNode(this);
		_SetCamera_001.addInput(_Sequence, 5);
		_SetCamera_001.addInput(new armory.logicnode.ObjectNode(this, "RearmView"), 0);
		_SetCamera_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sequence.addOutputs([_SetCamera_001]);
		_Sequence.addOutputs([_Merge_009]);
		_Sequence.addOutputs([_SetProperty]);
		_SetProperty_007.addInput(_Sequence, 0);
		_SetProperty_007.addInput(new armory.logicnode.ObjectNode(this, "White"), 0);
		_SetProperty_007.addInput(_GetProperty_005, 1);
		_SetProperty_007.addInput(_Boolean, 0);
		_SetProperty_007.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}